name: juejin autosign

on:
  push:
  schedule:
    - cron: "10 18 * * *"

jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # 使用 node:12
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # npm install
      - name: npm install and do sign
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
        run: |
          npm install
          node app.js
